// Code generated by "stringer -type=controlType"; DO NOT EDIT.

package chainsaw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ctrlDump-1]
	_ = x[ctrlRst-2]
	_ = x[ctrlQuit-3]
	_ = x[ctrlAddOutputChan-4]
	_ = x[ctrlRemoveOutputChan-5]
	_ = x[ctrlAddWriter-6]
	_ = x[ctrlRemoveWriter-7]
	_ = x[ctrlSetLogLevel-8]
	_ = x[ctrlFlush-9]
}

const _controlType_name = "ctrlDumpctrlRstctrlQuitctrlAddOutputChanctrlRemoveOutputChanctrlAddWriterctrlRemoveWriterctrlSetLogLevelctrlFlush"

var _controlType_index = [...]uint8{0, 8, 15, 23, 40, 60, 73, 89, 104, 113}

func (i controlType) String() string {
	i -= 1
	if i < 0 || i >= controlType(len(_controlType_index)-1) {
		return "controlType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _controlType_name[_controlType_index[i]:_controlType_index[i+1]]
}
