// Code generated by go generate; DO NOT EDIT.
// This file was generated by gen/main.go at 2021-11-08 19:21:41.552857 +0100 CET m=+0.000652251
package chainsaw

import (
	"fmt"
	"os"
)

func (l *CircularLogger) Trace(v ...interface{}) {
	s := fmt.Sprint(v...)
	l.log(TraceLevel, s)

}

func (l *CircularLogger) Tracef(f string, v ...interface{}) {
	s := fmt.Sprintf(f, v...)
	l.log(TraceLevel, s)

}

func Trace(v ...interface{}) {
	l := defaultLogger
	l.Trace(v...)
}

func Tracef(f string, v ...interface{}) {
	l := defaultLogger
	l.Tracef(f, v...)
}
func (l *CircularLogger) Debug(v ...interface{}) {
	s := fmt.Sprint(v...)
	l.log(DebugLevel, s)

}

func (l *CircularLogger) Debugf(f string, v ...interface{}) {
	s := fmt.Sprintf(f, v...)
	l.log(DebugLevel, s)

}

func Debug(v ...interface{}) {
	l := defaultLogger
	l.Debug(v...)
}

func Debugf(f string, v ...interface{}) {
	l := defaultLogger
	l.Debugf(f, v...)
}
func (l *CircularLogger) Info(v ...interface{}) {
	s := fmt.Sprint(v...)
	l.log(InfoLevel, s)

}

func (l *CircularLogger) Infof(f string, v ...interface{}) {
	s := fmt.Sprintf(f, v...)
	l.log(InfoLevel, s)

}

func Info(v ...interface{}) {
	l := defaultLogger
	l.Info(v...)
}

func Infof(f string, v ...interface{}) {
	l := defaultLogger
	l.Infof(f, v...)
}
func (l *CircularLogger) Warn(v ...interface{}) {
	s := fmt.Sprint(v...)
	l.log(WarnLevel, s)

}

func (l *CircularLogger) Warnf(f string, v ...interface{}) {
	s := fmt.Sprintf(f, v...)
	l.log(WarnLevel, s)

}

func Warn(v ...interface{}) {
	l := defaultLogger
	l.Warn(v...)
}

func Warnf(f string, v ...interface{}) {
	l := defaultLogger
	l.Warnf(f, v...)
}
func (l *CircularLogger) Error(v ...interface{}) {
	s := fmt.Sprint(v...)
	l.log(ErrorLevel, s)

}

func (l *CircularLogger) Errorf(f string, v ...interface{}) {
	s := fmt.Sprintf(f, v...)
	l.log(ErrorLevel, s)

}

func Error(v ...interface{}) {
	l := defaultLogger
	l.Error(v...)
}

func Errorf(f string, v ...interface{}) {
	l := defaultLogger
	l.Errorf(f, v...)
}
func (l *CircularLogger) Fatal(v ...interface{}) {
	s := fmt.Sprint(v...)
	l.log(FatalLevel, s)
	os.Exit(1)
}

func (l *CircularLogger) Fatalf(f string, v ...interface{}) {
	s := fmt.Sprintf(f, v...)
	l.log(FatalLevel, s)
	os.Exit(1)
}

func Fatal(v ...interface{}) {
	l := defaultLogger
	l.Fatal(v...)
}

func Fatalf(f string, v ...interface{}) {
	l := defaultLogger
	l.Fatalf(f, v...)
}
