// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package chainsaw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TraceLevel-1]
	_ = x[DebugLevel-2]
	_ = x[InfoLevel-3]
	_ = x[WarnLevel-4]
	_ = x[ErrorLevel-5]
	_ = x[FatalLevel-6]
}

const _LogLevel_name = "TraceLevelDebugLevelInfoLevelWarnLevelErrorLevelFatalLevel"

var _LogLevel_index = [...]uint8{0, 10, 20, 29, 38, 48, 58}

func (i LogLevel) String() string {
	i -= 1
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
